version: '2'
services:
  etcd:
    image: "elcolio/etcd"
    container_name: etcd
    restart: always
    ports:
     - "2379:2379"
     - "2380:2380"
     - "4001:4001"
     - "7001:7001"
  rabbitmq:
     image: rabbitmq
     container_name: rabbitmq
     restart: always
     ports:
       - "5672:5672"
       - "15672:15672"
  postgis:
    image: "mdillon/postgis"
    container_name: postgis
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user21
      POSTGRES_DB: video_portal
    ports:
     - "5432:5432"
  redis:
    image: "redis"
    command: redis-server --requirepass redis21
    container_name: redis
    restart: always
    ports:
     - "6379:6379"
